## Assignment 1 - Gradient Descent Algorithms with PyTorch
The following code cell is used to generate some noisy data (don't change this code).  You will need to use the data generated here to train a linear model $y=ax+b$ (i.e., Perform gradient descent on the two parameters $a$ and $b$). 


1.   You will need to code two algorithms (1) Gradient Descent + regular momentum, and (2) Adam, using PyTorch "autograd".
2.   Check your results against the linear regression model. You can do linear regression using "sklearn.linear_model" (Hint: you need to convert tensor to numpy array.)






In [1]:
import torch
torch.manual_seed(42)
x = torch.rand(100,1)
y = 1 + 2 * x + .1 * torch.rand(100, 1)

In [2]:
a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
a, b

(tensor([-0.6430], requires_grad=True), tensor([0.7113], requires_grad=True))

## Your code goes here:

In [3]:
aa = a
bb = b

In [4]:
train_loader = torch.cat([x,y],1)
train_loader.shape

torch.Size([100, 2])

In [5]:
from torch.nn import MSELoss
#from torch.optim import SGD,Adam

#optimizer = SGD([a,b], lr=1e-3, momentum=0.95)
loss_fn = MSELoss()
lr = 1e-3 

running_loss = 0.0
epochs = 30
for epoch in range(epochs):
    v_a = torch.tensor(([0]),dtype=torch.float)
    v_b = torch.tensor(([0]),dtype=torch.float)
    for batch in train_loader:
        a = torch.tensor([a], requires_grad=True)
        b = torch.tensor([b], requires_grad=True)
        m, n = batch
        preds = a*m + b
        loss = loss_fn(preds, n)
        loss.backward()
        v_a = 0.95 * v_a + a.grad
        v_b = 0.95 * v_b + b.grad
        v_a.requires_grad = False
        v_b.requires_grad = False
        a = a - lr * v_a
        b = b - lr * v_b 
        running_loss += loss.item()
    print(("Epoch:",epoch+1, "Loss:",running_loss/len(train_loader)))
    running_loss = 0.0
print(a,b)

C:\Users\gs70055\Anaconda3\envs\su\lib\site-packages\torch\nn\modules\loss.py:528: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


('Epoch:', 1, 'Loss:', 0.9364055199837458)
('Epoch:', 2, 'Loss:', 0.15476775919403735)
('Epoch:', 3, 'Loss:', 0.10187073704061789)
('Epoch:', 4, 'Loss:', 0.06569679600195741)
('Epoch:', 5, 'Loss:', 0.04256844145369541)
('Epoch:', 6, 'Loss:', 0.02767523824343698)
('Epoch:', 7, 'Loss:', 0.018090252663087086)
('Epoch:', 8, 'Loss:', 0.011921936206565533)
('Epoch:', 9, 'Loss:', 0.00795285160516869)
('Epoch:', 10, 'Loss:', 0.0053992455031720964)
('Epoch:', 11, 'Loss:', 0.0037566226674016433)
('Epoch:', 12, 'Loss:', 0.0027002321166601463)
('Epoch:', 13, 'Loss:', 0.0020210451711801625)
('Epoch:', 14, 'Loss:', 0.0015845225137633178)
('Epoch:', 15, 'Loss:', 0.0013040856593624995)
('Epoch:', 16, 'Loss:', 0.0011240265802808834)
('Epoch:', 17, 'Loss:', 0.0010084910241630496)
('Epoch:', 18, 'Loss:', 0.0009344255778695753)
('Epoch:', 19, 'Loss:', 0.0008869943905392574)
('Epoch:', 20, 'Loss:', 0.0008566562247779075)
('Epoch:', 21, 'Loss:', 0.0008373003928359424)
('Epoch:', 22, 'Loss:', 0.0008249585231

In [6]:
from torch.nn import MSELoss
from torch.optim import Adam

a = aa 
b = bb

optimizer = Adam([a,b], lr=1e-2)
loss_fn = MSELoss()

running_loss = 0.0
epochs = 30
for epoch in range(epochs):
    for batch in train_loader:
        m, n = batch
        preds = a*m + b
        loss = loss_fn(preds, n)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        #print(loss.item())
        running_loss += loss.item()
    print(("Epoch:",epoch+1, "Loss:",running_loss/len(train_loader)))
    running_loss = 0.0
print(a,b)

('Epoch:', 1, 'Loss:', 1.9046681172435638)
('Epoch:', 2, 'Loss:', 0.45292966659497325)
('Epoch:', 3, 'Loss:', 0.21255243357285508)
('Epoch:', 4, 'Loss:', 0.16313746707448445)
('Epoch:', 5, 'Loss:', 0.13129399892564833)
('Epoch:', 6, 'Loss:', 0.10371002784144366)
('Epoch:', 7, 'Loss:', 0.07998817684216192)
('Epoch:', 8, 'Loss:', 0.06022684182717057)
('Epoch:', 9, 'Loss:', 0.044280735114734855)
('Epoch:', 10, 'Loss:', 0.03179911006706334)
('Epoch:', 11, 'Loss:', 0.022316238234789124)
('Epoch:', 12, 'Loss:', 0.015323684040849913)
('Epoch:', 13, 'Loss:', 0.010321764795526179)
('Epoch:', 14, 'Loss:', 0.006853839183604577)
('Epoch:', 15, 'Loss:', 0.004525926434155281)
('Epoch:', 16, 'Loss:', 0.0030149358391918213)
('Epoch:', 17, 'Loss:', 0.002067952577220353)
('Epoch:', 18, 'Loss:', 0.0014958178928753795)
('Epoch:', 19, 'Loss:', 0.0011632249372452463)
('Epoch:', 20, 'Loss:', 0.0009775779800492046)
('Epoch:', 21, 'Loss:', 0.0008783370340057673)
('Epoch:', 22, 'Loss:', 0.0008276862218060899)
(

In [7]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(x, y)

LinearRegression()

In [8]:
regr.coef_

array([[2.0108864]], dtype=float32)

In [9]:
regr.intercept_

array([1.0401307], dtype=float32)