## Assignment 1 - Gradient Descent Algorithms with PyTorch
The following code cell is used to generate some noisy data (don't change this code).  You will need to use the data generated here to train a linear model $y=ax+b$ (i.e., Perform gradient descent on the two parameters $a$ and $b$). 


1.   You will need to code two algorithms (1) Gradient Descent + regular momentum, and (2) Adam, using PyTorch "autograd".
2.   Check your results against the linear regression model. You can do linear regression using "sklearn.linear_model" (Hint: you need to convert tensor to numpy array.)






In [1]:
import torch
torch.manual_seed(42)
x = torch.rand(100,1)
y = 1 + 2 * x + .1 * torch.rand(100, 1)

In [2]:
a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
a, b

(tensor([-0.6430], requires_grad=True), tensor([0.7113], requires_grad=True))

## Your code goes here:

In [3]:
train_loader = torch.cat([x,y],1)
train_loader.shape

torch.Size([100, 2])

In [4]:
from torch.nn import MSELoss
from torch.optim import SGD,Adam

optimizer = SGD([a,b], lr=1e-3, momentum=0.95)
loss_fn = MSELoss()

running_loss = 0.0
epochs = 30
for epoch in range(epochs):
    for batch in train_loader:
        m, n = batch
        preds = a*m + b
        loss = loss_fn(preds, n)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        #print(loss.item())
        running_loss += loss.item()
    print(("Epoch:",epoch+1, "Loss:",running_loss/len(train_loader)))
    running_loss = 0.0
print(a,b)

C:\Users\gs70055\Anaconda3\envs\su\lib\site-packages\torch\nn\modules\loss.py:528: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


('Epoch:', 1, 'Loss:', 0.9364055199837458)
('Epoch:', 2, 'Loss:', 0.13793398094247095)
('Epoch:', 3, 'Loss:', 0.07979742394047207)
('Epoch:', 4, 'Loss:', 0.04549877153505804)
('Epoch:', 5, 'Loss:', 0.02598368959443178)
('Epoch:', 6, 'Loss:', 0.014988622188948284)
('Epoch:', 7, 'Loss:', 0.00878952315197239)
('Epoch:', 8, 'Loss:', 0.005295818898866855)
('Epoch:', 9, 'Loss:', 0.0033279871555168938)
('Epoch:', 10, 'Loss:', 0.0022204540438860933)
('Epoch:', 11, 'Loss:', 0.0015977751878335767)
('Epoch:', 12, 'Loss:', 0.0012481764408590833)
('Epoch:', 13, 'Loss:', 0.0010522587835352225)
('Epoch:', 14, 'Loss:', 0.000942745598996595)
('Epoch:', 15, 'Loss:', 0.000881735633538483)
('Epoch:', 16, 'Loss:', 0.0008479142187047728)
('Epoch:', 17, 'Loss:', 0.0008292761065270326)
('Epoch:', 18, 'Loss:', 0.0008191044814935822)
('Epoch:', 19, 'Loss:', 0.0008136271994737854)
('Epoch:', 20, 'Loss:', 0.0008107277791255285)
('Epoch:', 21, 'Loss:', 0.0008092396902164012)
('Epoch:', 22, 'Loss:', 0.0008085107543

In [5]:
from torch.nn import MSELoss
from torch.optim import SGD,Adam

optimizer = Adam([a,b], lr=1e-3)
loss_fn = MSELoss()

running_loss = 0.0
epochs = 30
for epoch in range(epochs):
    for batch in train_loader:
        m, n = batch
        preds = a*m + b
        loss = loss_fn(preds, n)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        #print(loss.item())
        running_loss += loss.item()
    print(("Epoch:",epoch+1, "Loss:",running_loss/len(train_loader)))
    running_loss = 0.0
print(a,b)

('Epoch:', 1, 'Loss:', 0.0007609089023208071)
('Epoch:', 2, 'Loss:', 0.0007833293968668898)
('Epoch:', 3, 'Loss:', 0.0007830142439821941)
('Epoch:', 4, 'Loss:', 0.0007830120383107441)
('Epoch:', 5, 'Loss:', 0.0007830069671747708)
('Epoch:', 6, 'Loss:', 0.0007830038907360404)
('Epoch:', 7, 'Loss:', 0.0007830051996519671)
('Epoch:', 8, 'Loss:', 0.0007830015875653373)
('Epoch:', 9, 'Loss:', 0.0007830007780468407)
('Epoch:', 10, 'Loss:', 0.0007829998075779088)
('Epoch:', 11, 'Loss:', 0.0007830004367794175)
('Epoch:', 12, 'Loss:', 0.0007829965527345451)
('Epoch:', 13, 'Loss:', 0.0007829982547322345)
('Epoch:', 14, 'Loss:', 0.0007829939632200933)
('Epoch:', 15, 'Loss:', 0.0007829969125261016)
('Epoch:', 16, 'Loss:', 0.0007829922261466038)
('Epoch:', 17, 'Loss:', 0.0007829910930600192)
('Epoch:', 18, 'Loss:', 0.0007829863582783503)
('Epoch:', 19, 'Loss:', 0.0007829893893075735)
('Epoch:', 20, 'Loss:', 0.0007829892342444112)
('Epoch:', 21, 'Loss:', 0.0007829908352518089)
('Epoch:', 22, 'Loss:'

In [6]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(x, y)

LinearRegression()

In [7]:
regr.coef_

array([[2.0108864]], dtype=float32)

In [8]:
regr.intercept_

array([1.0401307], dtype=float32)

# Conclusion: 

 - Adma shows much faster convergence than SGD&Momentum from the perspective of loss. 